project_id = "qivroruezcxdnueuojkg"

[functions.whatsapp-webhook]
verify_jwt = false

[functions.booking-system]
verify_jwt = false

[functions.paypal-webhook]
verify_jwt = false

[functions.test-paypal]
verify_jwt = false

[functions.payment-paypal]
verify_jwt = false

[functions.payment-stripe]
verify_jwt = false